### ISSUE TITLE
Allow same shortcut key to launch and close tools.

### ISSUE THREAD

**Issue by alffrey** [pavanpodila/quicklens-uservoice#21]
When the user launches a tool from the "Tool" menu, it adds a checkmark to indicate the available tool. Traditionally, this indicates a toggle where the user can click on it again to close the tool which is not the case here. The user has to go to "Window" -> "Close window" to achieve this which is not intuitive.

Can we have the "Tool" menu options and the shortcut keys to behave like a toggle.

**Comment by pavanpodila** [comment]
The reason why we kept those shortcuts separate is because some tools allow multiple instances, such as Lens and Ruler. So hitting the same shortcut will launch more instances. Perhaps we can launch more instances with an Option Key instead of the tool shortcut ? That can allow a toggle-like behavior. We can still keep Cmd+W to close since this is standard on Mac to close windows.

**Comment by pavanpodila** [comment]
The other option is to make the Status menu a toggle just like the tool palette

**Comment by pavanpodila** [comment]
The global shortcuts behave this way.
